# Generated by Django 5.2 on 2025-04-07 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('changes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('REGULAR', 'Regular Savings'), ('FIXED', 'Fixed Deposit'), ('JUNIOR', 'Junior Savings'), ('RETIREMENT', 'Retirement Savings')], max_length=20, verbose_name='Account Type')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Balance')),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Minimum Balance')),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Opened')),
                ('date_closed', models.DateTimeField(blank=True, null=True, verbose_name='Date Closed')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed'), ('FROZEN', 'Frozen')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interest Rate (%)')),
                ('last_interest_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Last Interest Calculation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
            },
        ),
        migrations.CreateModel(
            name='ShareCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=20, unique=True, verbose_name='Certificate Number')),
                ('number_of_shares', models.PositiveIntegerField(verbose_name='Number of Shares')),
                ('value_per_share', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value Per Share')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Value')),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Purchased')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=15, verbose_name='Status')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly Contribution')),
                ('compensation_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Compensation Amount')),
                ('last_payment_date', models.DateField(null=True, verbose_name='Last Payment Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Capital',
                'verbose_name_plural': 'Share Capital',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INTEREST_EARNED', 'Interest Earned'), ('CHARGE', 'Charge/Fee'), ('DIVIDEND', 'Dividend Payment'), ('SHARE_PURCHASE', 'Share Purchase'), ('SHARE_SALE', 'Share Sale')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance After')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.savingsaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
