# Generated by Django 5.2 on 2025-04-07 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fund Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('date_established', models.DateField(default=django.utils.timezone.now, verbose_name='Date Established')),
                ('contribution_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('ONETIME', 'One Time')], default='MONTHLY', max_length=10, verbose_name='Contribution Frequency')),
                ('minimum_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Contribution')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Welfare Fund',
                'verbose_name_plural': 'Welfare Funds',
            },
        ),
        migrations.CreateModel(
            name='WelfareBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MEDICAL', 'Medical'), ('BEREAVEMENT', 'Bereavement'), ('EDUCATION', 'Education'), ('RETIREMENT', 'Retirement'), ('DISABILITY', 'Disability'), ('OTHER', 'Other')], max_length=20, verbose_name='Reason')),
                ('other_reason', models.TextField(blank=True, null=True, verbose_name='Other Reason Details')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Requested')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Amount')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('disbursement_date', models.DateTimeField(blank=True, null=True, verbose_name='Disbursement Date')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=15, verbose_name='Status')),
                ('has_documentation', models.BooleanField(default=False, verbose_name='Has Supporting Documents')),
                ('document_description', models.TextField(blank=True, null=True, verbose_name='Document Description')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_benefits', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_benefits', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_benefits', to=settings.AUTH_USER_MODEL)),
                ('welfare_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='welfare.welfarefund')),
            ],
            options={
                'verbose_name': 'Welfare Benefit',
                'verbose_name_plural': 'Welfare Benefits',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='WelfareDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='welfare_documents/', verbose_name='Document')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='welfare.welfarebenefit')),
            ],
            options={
                'verbose_name': 'Welfare Document',
                'verbose_name_plural': 'Welfare Documents',
            },
        ),
        migrations.CreateModel(
            name='WelfareContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Contribution Date')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receipt Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_contributions', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_welfare_contributions', to=settings.AUTH_USER_MODEL)),
                ('welfare_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='welfare.welfarefund')),
            ],
            options={
                'verbose_name': 'Welfare Contribution',
                'verbose_name_plural': 'Welfare Contributions',
                'ordering': ['-contribution_date'],
            },
        ),
    ]
