# Generated by Django 5.2 on 2025-04-12 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfarefund',
            name='date_established',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Established'),
        ),
    ]
