# Generated by Django 5.2 on 2025-04-07 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='Payment Status')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Calculation Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date_charged', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Charged')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', max_length=10, verbose_name='Status')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Date Paid')),
                ('waived', models.BooleanField(default=False, verbose_name='Waived')),
                ('waiver_reason', models.TextField(blank=True, null=True, verbose_name='Waiver Reason')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Fee Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('calculation_method', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('TIERED', 'Tiered')], max_length=10, verbose_name='Calculation Method')),
                ('rate_or_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Rate (%) or Amount')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Minimum Amount')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Maximum Amount')),
                ('application_frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('ON_EVENT', 'On Event')], max_length=10, verbose_name='Application Frequency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
            ],
            options={
                'verbose_name': 'Financial Period',
                'verbose_name_plural': 'Financial Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID Number')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10, verbose_name='Status')),
                ('total_shares', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Shares')),
                ('registration_paid', models.BooleanField(default=False, verbose_name='Registration Paid')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('mpesa_receipt', models.CharField(blank=True, max_length=20, null=True, verbose_name='M-Pesa Receipt')),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Checkout Request ID')),
                ('is_initial_payment', models.BooleanField(default=False, verbose_name='Is Initial Payment')),
            ],
            options={
                'verbose_name': 'Membership Fee',
                'verbose_name_plural': 'Membership Fees',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('source', models.CharField(choices=[('REGISTRATION', 'Registration Fee'), ('LOAN_INTEREST', 'Loan Interest'), ('PENALTIES', 'Penalties'), ('OTHER', 'Other Sources')], max_length=20, verbose_name='Profit Source')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Recorded')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID')),
            ],
            options={
                'verbose_name': 'Profit',
                'verbose_name_plural': 'Profits',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10, verbose_name='Transaction Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Savings',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.PositiveIntegerField(verbose_name='Number of Shares')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
            ],
        ),
    ]
