# Generated by Django 5.2 on 2025-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaconfig', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the transaction', max_length=255, null=True),
        ),
    ]
