# Generated by Django 5.2 on 2025-04-07 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('OTHER', 'Other')], max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entity ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('document_type', models.CharField(choices=[('POLICY', 'Policy Document'), ('CONTRACT', 'Contract'), ('REPORT', 'Report'), ('FORM', 'Form'), ('MINUTES', 'Meeting Minutes'), ('OTHER', 'Other')], max_length=15, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SYSTEM', 'System'), ('TRANSACTION', 'Transaction'), ('ACCOUNT', 'Account'), ('LOAN', 'Loan'), ('WELFARE', 'Welfare'), ('DIVIDEND', 'Dividend')], max_length=15, verbose_name='Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DATE', 'Date'), ('DATETIME', 'DateTime')], max_length=10, verbose_name='Data Type')),
                ('setting_type', models.CharField(choices=[('GENERAL', 'General'), ('SYSTEM', 'System'), ('LOAN', 'Loan'), ('SAVINGS', 'Savings'), ('WELFARE', 'Welfare'), ('NOTIFICATION', 'Notification')], max_length=15, verbose_name='Setting Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
