# Generated by Django 5.2 on 2025-04-05 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Penalty Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('calculation_method', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], max_length=10, verbose_name='Calculation Method')),
                ('rate_or_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Rate (%) or Amount')),
                ('grace_period_days', models.PositiveIntegerField(default=0, verbose_name='Grace Period (Days)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Penalty Type',
                'verbose_name_plural': 'Penalty Types',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=20, unique=True, verbose_name='Loan ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('EMERGENCY', 'Emergency Loan'), ('EDUCATION', 'Education Loan'), ('ASSET', 'Asset Financing')], max_length=15, verbose_name='Loan Type')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (% p.a.)')),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('REDUCING', 'Reducing Balance')], default='REDUCING', max_length=15, verbose_name='Interest Type')),
                ('term_months', models.PositiveIntegerField(verbose_name='Loan Term (Months)')),
                ('repayment_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=10, verbose_name='Repayment Frequency')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('disbursement_date', models.DateTimeField(blank=True, null=True, verbose_name='Disbursement Date')),
                ('first_payment_date', models.DateField(blank=True, null=True, verbose_name='First Payment Date')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Maturity Date')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('FULLY_PAID', 'Fully Paid'), ('DEFAULTED', 'Defaulted'), ('WRITTEN_OFF', 'Written Off'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=15, verbose_name='Status')),
                ('purpose', models.TextField(verbose_name='Loan Purpose')),
                ('total_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Interest')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount (Principal + Interest)')),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monthly Installment')),
                ('principal_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Principal Balance')),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Interest Balance')),
                ('has_collateral', models.BooleanField(default=False, verbose_name='Has Collateral')),
                ('collateral_details', models.TextField(blank=True, null=True, verbose_name='Collateral Details')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranteed_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Guaranteed Amount')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Response Date')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=10, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Guarantor',
                'verbose_name_plural': 'Guarantors',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount')),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Component')),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Component')),
                ('penalties_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Penalties Component')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Payment Method')),
                ('transaction_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Reference')),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Receipt Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('principal_balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Balance After')),
                ('interest_balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Balance After')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date_imposed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Imposed')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('IMPOSED', 'Imposed'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='IMPOSED', max_length=10, verbose_name='Status')),
                ('waived', models.BooleanField(default=False, verbose_name='Waived')),
                ('waiver_reason', models.TextField(blank=True, null=True, verbose_name='Waiver Reason')),
                ('waived_at', models.DateTimeField(blank=True, null=True, verbose_name='Waived At')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.loan')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL)),
                ('penalty_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_penalties', to='loans.penaltytype')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
            },
        ),
    ]
