# Generated by Django 5.2 on 2025-04-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approvals_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Penalty Amount'),
        ),
        migrations.AddField(
            model_name='loan',
            name='pending_approvals',
            field=models.ManyToManyField(blank=True, help_text='Admins who still need to approve this loan', related_name='pending_loan_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('TWO_MONTHS', 'Every Two Months'), ('THREE_MONTHS', 'Every Three Months'), ('FOUR_MONTHS', 'Every Four Months')], default='MONTHLY', max_length=20, verbose_name='Repayment Period'),
        ),
        migrations.CreateModel(
            name='GuarantorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_requests_received', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_requests', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approvals', to='loans.loan')),
            ],
            options={
                'unique_together': {('loan', 'admin')},
            },
        ),
    ]
