# Generated by Django 5.2 on 2025-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_approvals_completed_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Application Date'),
        ),
    ]
